// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czvnmmggztfgxkaffshv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6dm5tbWdnenRmZ3hrYWZmc2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTI2OTUsImV4cCI6MjA2NjY4ODY5NX0.cSpJ4uNymRvBM2baaMLEDUlulyV_XEzefoOMr6il2tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);